### ISSUE TITLE
[docker-compose] Avoid chmod 777 on folders

### ISSUE THREAD

**Issue by antonionardella** [iotaledger/goshimmer#623]
## Description
In the wiki it is written to `chmod 0777` or `chmod 777` different directories like the `db` folder or `grafana`.
To avoid this use of permissions on directories it is possible to use the parameter `user: "UID:GID"` in the docker-compose file.

### `GoShimmer` section of the docker-compose

For GoShimmer `user: "0:0"` works and you can avoid `mkdir db`:
```
services:
  goshimmer:
    image: iotaledger/goshimmer:v0.2.1
    container_name: goshimmer
    hostname: goshimmer
    restart: unless-stopped
    user: "0:0"
    volumes:
      - "./db:/tmp/mainnetdb:rw"
      - "/etc/localtime:/etc/localtime:ro"
[...]
```

This will automatically create the `db` directory owned by root on the host.

### `Grafana` section of the docker-compose

To get grafana running correctly, use `user: "472:0"`:

```
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    user: "472:0"
[...]
```
And on the `grafana` directory that contains the datasource and dashboard use `chown -R 472:0 grafana`.

### `Prometheus` section of the docker-compose
For Prometheus `user: "0:0"` works, if you have created the folders and files as `root` user:
```
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    user: "0:0"
    ports:
      - "9090:9090/tcp"
[...]
```

## Motivation

https://stackoverflow.com/questions/14994975/avoid-hacking-with-folder-has-chmod-is-777

## Are you planning to do it yourself in a pull request?

No, I cannot do pull requests for the wiki page.
